- name: enable nginx1
  shell: |
    amazon-linux-extras enable nginx1

- name: install nginx
  yum:
    name:
      - nginx
    state: present

- name: restart & enable nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
