version: "3.9"
volumes:
  php-fpm-socket:
  db-store:
  psysh-store:
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./src
        target: /work/src
      - type: bind
        source: ~/.ssh
        target: /root/.ssh
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
    env_file:
      - docker/php/.env
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_NAME:-laravel_local}
      - DB_USERNAME=${DB_USER:-phper}
      - DB_PASSWORD=${DB_PASS:-secret}
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_DEFAULT_OUTPUT=json

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - target: 80
        published: ${WEB_PORT:-80}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./src
        target: /work/src

  # db:
  #   build:
  #     context: .
  #     dockerfile: ./docker/mysql/Dockerfile
  #   ports:
  #     - target: 3306
  #       published: ${DB_PORT:-3306}
  #       protocol: tcp
  #       mode: host
  #   volumes:
  #     - type: volume
  #       source: db-store
  #       target: /var/lib/mysql
  #       volume:
  #         nocopy: true
  #   environment:
  #     - MYSQL_DATABASE=${DB_NAME:-laravel_local}
  #     - MYSQL_USER=${DB_USER:-phper}
  #     - MYSQL_PASSWORD=${DB_PASS:-secret}
  #     - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}
  # for image postgres
  db:
    image: postgres:9.6
    container_name: db
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: 'docker'
      POSTGRES_DB: 'laravel_development'
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
      # - ./docker/db/data:/var/lib/postgresql/data
      # - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
